#logging:
#  level:
#    root: DEBUG
spring:
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
personal:
  email: ${PERSONAL_EMAIL}
  admin:
    username: ${ADMIN_USER}
    password: ${ADMIN_PASSWORD}