#logging:
#  level:
#    root: TRACE
spring:
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security.oauth2.client.registration.github:
    clientId: ${GH_CLIENT_ID}
    clientSecret: ${GH_CLIENT_SECRET}
personal:
  email: ${PERSONAL_EMAIL}
  admin:
    usernames:
      github: ${GH_ADMIN_USER}
google.recaptcha.key:
  site: ${SITE_KEY}
  key: ${SECRET_KEY}
  threshold: 0.7
